stages:
- test
- publish

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true

test:
  stage: test
  script:
    - sbt clean update test

publish:
  stage: publish
  script: 
    - sbt publish

github-publish:
  stage: publish
  script: 
    - git remote remove github || true
    - git remote add github https://$GITHUB_CREDENTIALS@github.com/GalacticFog/gestalt-security-sdk-scala.git
    - |
      if [ -z ${CI_BUILD_TAG} ]; then 
         git push github HEAD:$CI_BUILD_REF_NAME
      else 
         git push github $CI_BUILD_TAG
      fi
  only:
    - master
    - /^release-.*$/
    - tags

